### ISSUE TITLE
[Mob] Brigandish Blade

### ISSUE THREAD

**Issue by eraffxi-personal** [eraffxi-personal/LSB#2]
https://ffxiclopedia.fandom.com/wiki/Brigandish_Blade
possibly make custom added effect on the buccaneers knife to remove dmg immunity buff on NM

**Comment by eraffxi-personal** [comment]
Killable, needs unkillable flag and make knife remove flag

**Comment by Judaine** [comment]
- ✅ Unable to kill after Brigandish_Blade.lua change.
- ✅ Inserted item_mods rows for Buccaneer's Knife into DB.
- ✅ Added REMOVE_UNKILLABLE effect type (13) into additional_effects.lua
- ✅ Added logic for REMOVE_UNKILLABLE only proccing on Brigandish Blade into additional_effects.lua.
- ✅ Unable to kill BB without the knife, able to kill with it.
- ✅ Can kill after tagging at the beginning.
- ✅ BB has to be hit with the knife for unkillable status to be disabled.

[Commit: Added unkillable effect to Brigandish Blade](https://github.com/eraffxi/LSB/commit/4f71b3d8048a49e9f399c0ab43ecb2c7990e6d94)

Implemented the following changes:

### **Database**
Credits: @Judaine 
**Query**: `INSERT INTO item_mods(itemId, modId, value)
	VALUES(17622, 431, 13), 
		(17622, 501, 100)`


### **LUA**
### scripts/globals/additional_effects.lua
Credits: @RunAwayDSP for zone variable, @Judaine for other implementation.
**Insert @ Line 123:**  `REMOVE_UNKILLABLE = 13, --Solely for Buccaneer's Knife with Brigandish Blade`
![image](https://user-images.githubusercontent.com/19351709/165440688-d75acdc9-4250-4c5f-b1f6-4061cf5a71d7.png)

**Remove @ Line 255:** `end`

**Insert @ Line 258:**
`elseif addType == procType.REMOVE_UNKILLABLE then
        local BBID   = require('scripts/zones/VELUGANNON_PALACE/IDs')
        if
            GetMobByID(BBID.mob.BRIGANDISH_BLADE)
        then
            defender:setUnkillable(false)
        else
            return 0, 0, 0 -- Not Brigandish Blade
        end
    end`

![image](https://user-images.githubusercontent.com/19351709/165440751-5e971277-0e06-4958-8d34-4fea8737e3c2.png)

### scripts/zones/VeLugannon_Palace/mobs/Brigandish_Blade.lua
Credits: @eraffxi
**Insert @ Line 14:** `entity.onMobSpawn = function(mob)
	mob:setUnkillable(true)
end`
![image](https://user-images.githubusercontent.com/19351709/165441336-9a771cbc-9bba-46b7-8c70-c4769320148e.png)

**Comment by jefferyrlc** [comment]
Tested the knife on Tinnin, does not remove it's unkillable status.

**Comment by jefferyrlc** [comment]
Correction. It makes it no longer work on Brigandish Blade either.

**Comment by austinclprojects** [comment]
This should be in a branch and PRed into the main branch when ready.

**Comment by austinclprojects** [comment]
Were there SQL changes?

**Comment by RunAwayDSP** [comment]
"Database
Credits: @Judaine
Query: INSERT INTO item_mods(itemId, modId, value) VALUES(17622, 431, 13), (17622, 501, 100)
"

**Comment by austinclprojects** [comment]
That needs to be added to the item_mods.sql or it will be lost on next import.
